modLoader="javafml" #mandatory
loaderVersion="[37,)" #mandatory (37 is current forge version)
license="MIT License"

[[mods]] #mandatory
modId="structure_tutorial" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Structure Tutorial Mod" #mandatory
credits="Special thanks to nhwhite3118 for helping out!"
authors="TelepathicGrunt" #optional
description='''
A short mod example on how to register structures and generate them in any biome using structure nbt files.
'''

# makes sure our mod does not be attempted to be ran on older version of Minecraft and explodes
[[dependencies.structure_tutorial]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.0, 1.18.0)"